name: bricks_breaker
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flame: ^1.8.0
  flame_audio: ^2.0.0
  flutter:
    sdk: flutter
  amplify_flutter: ^1.0.0
  amplify_auth_cognito: ^1.0.0
  amplify_authenticator: ^1.0.0
  amplify_api: ^1.0.0
  flutter_riverpod: ^2.0.0
  riverpod_annotation: ^2.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  amplify_lints: ^3.0.0
  build_runner:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.0.0
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/audio/


